### PR TITLE
Problem: Outdated tutorials and demos for v0.0.9-alpha (fix cronos-labs/play-unreal-plugin#196)

### PR DESCRIPTION
**Pull request by damoncro**
Close:
- cronos-labs/play-unreal-plugin#196

Solutions:
- Add walletconnet demo for [tutorial](https://docs.cronos.org/cronos-play/getting-started_unreal/quick-start/walletconnect)
- Update the simple demo for v0.0.9-alpha

### CODE REVIEW

**Comment by damoncro** [comment]
Help review https://github.com/crypto-org-chain/cronos-docs/pull/272 as well, which is updated for aligning with v0.0.9-alpha.

**Comment by damoncro** [comment]
v0.0.9-alpha is not available in marketplace yet, we could wait it to be approved first before merging.

**Review by tomtau — APPROVED** [review]
I guess there's no diff, just new blueprints?

**Comment by damoncro** [comment]
New blueprints for tutorial, for the simple demo, simply replace with renamed functions.

**Comment by damoncro** [comment]
Just checked v0.0.9-alpha was updated on marketplace! This PR is ready to be merged.

**Comment by tomtau** [comment]
those uproject URLs remain the same?

**Comment by damoncro** [comment]
DocURL is updated. Others retain.

**Pull request merged**
