### PR TITLE
Problem: Metaverse example not updated (fix #330)

### PR DESCRIPTION
**Pull request by leejw51crypto**
tidy up

remove debug display

callback in app

tidy up

restore

update dynamic contract info

### CODE REVIEW

**Comment by leejw51crypto** [comment]
fixing ci errors

**Comment by leejw51crypto** [comment]
checking demo projects

**Review by rarcifa — APPROVED** [review]
lgtm

**Review by rarcifa — COMMENTED** [review]
Problem: Metaverse example not updated (fix #330) #177 other than that looks good

**Pull request merged**
