### PR TITLE
Problem: Missing android support for play-unreal-demo (fix cronos-labs/play-unreal-plugin#153)

### PR DESCRIPTION
**Pull request by damoncro**
Close:
- cronos-labs/play-unreal-plugin#153

Solutions:
- Move assets from play-unreal-plugin to play-unreal-demo
- Use play-unreal-plugin v0.0.7-alpha
- Add android configurations
- Update github action to release Asset Pack

### CODE REVIEW

**Comment by leejw51crypto** [comment]
keystroke is necessary, can be stored not in the repo?
instead like github server?

**Comment by damoncro** [comment]
> keystroke is necessary?, can be stored not in the repo? instead like github server?

It is a test key, it should be in the repo for easy build. Without it, we can not build android apk. It was generated by https://github.com/cronos-labs/play-unreal-demo/pull/20/files#diff-32e21d0a0eba3262b2fca376ed9589da982b5a1476823c7408d6a09de720879d.

**Comment by leejw51crypto** [comment]
i suggest
- register keystroke in env variable which, only admin can see
- write it to this file on the fly

even though it's testkey, in production,
user may replace with real-one,  make a mistake to open public

**Review by leejw51crypto — APPROVED** [review]
lgtm

**Pull request merged**
