### PR TITLE
Problem: missing api for tokenuri download and texture generation (fi…

### PR DESCRIPTION
**Pull request by leejw51crypto**
Solution: add erc721 example for token uri downloading and display

### CODE REVIEW

**Review by tomtau — COMMENTED** [review]
it seems this pr changes the code formatting ?

**Comment by leejw51crypto** [comment]
i'll check

**Review by tomtau — APPROVED** [review]
maybe some warning that the developer should be careful about user-generated content: https://github.com/cronos-labs/play-unreal-plugin/pull/76#pullrequestreview-1033747578 so that one doesn't blindly copy the demo code ?

**Comment by leejw51crypto** [comment]
ok, i'll include it in another pr

**Pull request merged**
