### PR TITLE
Problem: missing clang-format for metaverse c++ demo (fix #286)

### PR DESCRIPTION
**Pull request by leejw51crypto**
add .clang-format
add ignore files
add makefile for formatting

### CODE REVIEW

**Comment by leejw51crypto** [comment]
only reformatted

**Comment by damoncro** [comment]
Reformatting may break the BindDynamic andd AddDynamic statements (it is macro actually), may I know have you tested?

**Comment by damoncro** [comment]
The last time I reformat them, BindDynamic and AddDynamic failed to run. Need to manually format them.

**Comment by leejw51crypto** [comment]
ok, i'll double check

**Comment by leejw51crypto** [comment]
confirmed it working fine
i assume
```
SortIncludes: Never
IndentWidth: 4
BasedOnStyle: LLVM
```
no sorting includes,
added .clang-format, and Makefile for formatting
in top folder, make

**Review by tomtau — APPROVED** [review]

**Comment by damoncro** [comment]
The reformat breaks the code (mainly is what I mentioned):
```
LogOutputDevice: Error: === Handled ensure: ===
LogOutputDevice: Error: Ensure condition failed: this->IsBound()  [File:Runtime/Core/Public/Delegates/DelegateSignatureImpl.inl] [Line: 1037] 
LogOutputDevice: Error: Unable to bind delegate to ' OnWalletconnectSignEip155TransactionFinished' (function might not be marked as a UFUNCTION or object may be pending kill)
LogOutputDevice: Error: Stack: 
LogOutputDevice: Error: [Callstack] 0x93c7fa21 UnrealEditor-Metaverse-7475.dylib!void TBaseDynamicDelegate<FWeakObjectPtr, void, FWalletSignTXEip155Result>::__Internal_BindDynamic<UWalletConnectTriggerComponent>(UWalletConnectTriggerComponent*, TBaseDynamicDelegate<FWeakObjectPtr, void, FWalletSignTXEip155Result>::TMethodPtrResolver<UWalletConnectTriggerComponent>::FMethodPtr, FName)   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x93c7f809 UnrealEditor-Metaverse-7475.dylib!UWalletConnectTriggerComponent::BeginPlay()   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x18cc181c UnrealEditor-Engine.dylib!AActor::BeginPlay()   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x93c83fe4 UnrealEditor-Metaverse-7475.dylib!ASignEthTransaction::BeginPlay()   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x18cc09f5 UnrealEditor-Engine.dylib!AActor::DispatchBeginPlay(bool)   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x1af3093e UnrealEditor-Engine.dylib!AWorldSettings::NotifyBeginPlay()   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x198ae7f1 UnrealEditor-Engine.dylib!AGameStateBase::HandleBeginPlay()   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x1adef98f UnrealEditor-Engine.dylib!UWorld::BeginPlay()   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x19864ce0 UnrealEditor-Engine.dylib!UGameInstance::StartPlayInEditorGameInstance(ULocalPlayer*, FGameInstancePIEParameters const&)   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x21906112 UnrealEditor-UnrealEd.dylib!UEditorEngine::CreateInnerProcessPIEGameInstance(FRequestPlaySessionParams&, FGameInstancePIEParameters const&, int)   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x218f78f2 UnrealEditor-UnrealEd.dylib!UEditorEngine::OnLoginPIEComplete_Deferred(int, bool, FString, FPieLoginStruct)   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x218f9813 UnrealEditor-UnrealEd.dylib!UEditorEngine::CreateNewPlayInEditorInstance(FRequestPlaySessionParams&, bool, EPlayNetMode)   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x218fffcf UnrealEditor-UnrealEd.dylib!UEditorEngine::StartPlayInEditorSession(FRequestPlaySessionParams&)   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x218f4909 UnrealEditor-UnrealEd.dylib!UEditorEngine::StartQueuedPlaySessionRequestImpl()   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x218f3edb UnrealEditor-UnrealEd.dylib!UEditorEngine::StartQueuedPlaySessionRequest()   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x210bda1e UnrealEditor-UnrealEd.dylib!UEditorEngine::Tick(float, bool)   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x21d9fed8 UnrealEditor-UnrealEd.dylib!UUnrealEdEngine::Tick(float, bool)   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x0c6e7808 UnrealEditor!FEngineLoop::Tick()   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x0c6f476e UnrealEditor!GuardedMain(char16_t const*)   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x0c70f725 UnrealEditor!-[UEAppDelegate runGameThread:]   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x0e845cbc UnrealEditor-Core.dylib!-[FCocoaGameThread main]   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x1bb483bc Foundation!__NSThread__start__()   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x1ac19259 libsystem_pthread.dylib!_pthread_start()   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x1ac14c7b libsystem_pthread.dylib!thread_start()   [UnknownFile]) 
```

```
LogOutputDevice: Error: === Handled ensure: ===
LogOutputDevice: Error: Ensure condition failed: this->IsBound()  [File:Runtime/Core/Public/Delegates/DelegateSignatureImpl.inl] [Line: 1037] 
LogOutputDevice: Error: Unable to bind delegate to ' OnReceiveWalletconnectSessionInfoDelegateFinished' (function might not be marked as a UFUNCTION or object may be pending kill)
LogOutputDevice: Error: Stack: 
LogOutputDevice: Error: [Callstack] 0x93c81661 UnrealEditor-Metaverse-7475.dylib!void TBaseDynamicDelegate<FWeakObjectPtr, void, FWalletConnectSessionInfo>::__Internal_BindDynamic<UWalletConnectTriggerComponent>(UWalletConnectTriggerComponent*, TBaseDynamicDelegate<FWeakObjectPtr, void, FWalletConnectSessionInfo>::TMethodPtrResolver<UWalletConnectTriggerComponent>::FMethodPtr, FName)   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x93c80cd6 UnrealEditor-Metaverse-7475.dylib!UWalletConnectTriggerComponent::Connect()   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x93c86184 UnrealEditor-Metaverse-7475.dylib!AConnectWalletConnect::OnConnectWalletConnectBeginOverlap(UPrimitiveComponent*, AActor*, UPrimitiveComponent*, int, bool, FHitResult const&)   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x93c72dcf UnrealEditor-Metaverse-7475.dylib!AConnectWalletConnect::execOnConnectWalletConnectBeginOverlap(UObject*, FFrame&, void*)   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x100e525c UnrealEditor-CoreUObject.dylib!UFunction::Invoke(UObject*, FFrame&, void*)   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x103db95a UnrealEditor-CoreUObject.dylib!UObject::ProcessEvent(UFunction*, void*)   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x18c94413 UnrealEditor-Engine.dylib!AActor::ProcessEvent(UFunction*, void*)   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x18ce889a UnrealEditor-Engine.dylib!void TScriptDelegate<FWeakObjectPtr>::ProcessDelegate<UObject>(void*) const   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x18ce85e7 UnrealEditor-Engine.dylib!void TMulticastScriptDelegate<FWeakObjectPtr>::ProcessMulticastDelegate<UObject>(void*) const   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x1941d684 UnrealEditor-Engine.dylib!UPrimitiveComponent::BeginComponentOverlap(FOverlapInfo const&, bool)   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x1942164a UnrealEditor-Engine.dylib!UPrimitiveComponent::UpdateOverlapsImpl(TArrayView<FOverlapInfo const, int> const*, bool, TArrayView<FOverlapInfo const, int> const*)   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x1947cec6 UnrealEditor-Engine.dylib!USceneComponent::EndScopedMovementUpdate(FScopedMovementUpdate&)   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x197cb509 UnrealEditor-Engine.dylib!FScopedMovementUpdate::~FScopedMovementUpdate()   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x19359884 UnrealEditor-Engine.dylib!UCharacterMovementComponent::PerformMovement(float)   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x193750a5 UnrealEditor-Engine.dylib!UCharacterMovementComponent::ControlledCharacterMove(UE::Math::TVector<double> const&, float)   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x1934bfbc UnrealEditor-Engine.dylib!UCharacterMovementComponent::TickComponent(float, ELevelTick, FActorComponentTickFunction*)   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x192d1e1a UnrealEditor-Engine.dylib!FActorComponentTickFunction::ExecuteTick(float, ELevelTick, ENamedThreads::Type, TRefCountPtr<FGraphEvent> const&)   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x1ab4254f UnrealEditor-Engine.dylib!FTickFunctionTask::DoTask(ENamedThreads::Type, TRefCountPtr<FGraphEvent> const&)   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x1ab41e60 UnrealEditor-Engine.dylib!TGraphTask<FTickFunctionTask>::ExecuteTask(TArray<FBaseGraphTask*, TSizedDefaultAllocator<32> >&, ENamedThreads::Type, bool)   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x0e5ce37d UnrealEditor-Core.dylib!FNamedTaskThread::ProcessTasksNamedThread(int, bool)   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x0e5cc5fe UnrealEditor-Core.dylib!FNamedTaskThread::ProcessTasksUntilQuit(int)   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x0e5cab9f UnrealEditor-Core.dylib!FTaskGraphCompatibilityImplementation::ProcessThreadUntilRequestReturn(ENamedThreads::Type)   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x0e5cb187 UnrealEditor-Core.dylib!FTaskGraphCompatibilityImplementation::WaitUntilTasksComplete(TArray<TRefCountPtr<FGraphEvent>, TSizedInlineAllocator<4u, 32, TSizedDefaultAllocator<32> > > const&, ENamedThreads::Type)   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x1ab3a6d7 UnrealEditor-Engine.dylib!FTickTaskSequencer::ReleaseTickGroup(ETickingGroup, bool)   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x1ab33f4c UnrealEditor-Engine.dylib!FTickTaskManager::RunTickGroup(ETickingGroup, bool)   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x19bfe161 UnrealEditor-Engine.dylib!UWorld::Tick(ELevelTick, float)   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x210bea23 UnrealEditor-UnrealEd.dylib!UEditorEngine::Tick(float, bool)   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x21d9fed8 UnrealEditor-UnrealEd.dylib!UUnrealEdEngine::Tick(float, bool)   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x0c6e7808 UnrealEditor!FEngineLoop::Tick()   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x0c6f476e UnrealEditor!GuardedMain(char16_t const*)   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x0c70f725 UnrealEditor!-[UEAppDelegate runGameThread:]   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x0e845cbc UnrealEditor-Core.dylib!-[FCocoaGameThread main]   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x1bb483bc Foundation!__NSThread__start__()   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x1ac19259 libsystem_pthread.dylib!_pthread_start()   [UnknownFile]) 
LogOutputDevice: Error: [Callstack] 0x1ac14c7b libsystem_pthread.dylib!thread_start()   [UnknownFile]) 
```

**Pull request merged**
